// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksmxyzuayzjoanxngjai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbXh5enVheXpqb2FueG5namFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2Mzk0OTQsImV4cCI6MjA1NzIxNTQ5NH0.mp1EHl6CWOii9HlrgJ-Y5B5Bi3lb1s5ID-76tkEufxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);